name: GCC Problem Matcher with Build Dir Support
description: Attaches a problem matcher that looks for errors during gcc builds. Ignores ../ at the start of the file input.
author: Joshua Ashton (fork) and Ammar Askar
branding:
  icon: check-square
  color: purple
runs:
  using: 'node20'
  main: 'index.js'
